language: python

python:
     - "2.7"
     
notifications:
  email:
    recipients:
      - filters@adguard.com
    on_success: never
    on_failure: always

script:
    - python Filters/parser.py
    
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master    
